config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :items do
    resources :bookings, only: [ :new, :create]
  end
  resources :bookings, only: [:index, :show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zipcode, presence: true
  STATUS = ["approved", "pending", "rejected"]
  validates :status, inclusion: { in: STATUS }
end

app/models/item.rb
# "Tops", "Pants", "T-shirt", "Skirts and Shorts","Jackets", "Coats", "Tailoring"
# Could add these to CATEGORY but keeping it small for now

class Item < ApplicationRecord
  has_many :bookings
  has_one_attached :photo
  belongs_to :user
  CATEGORY = ["Clothing", "Bags", "Accessories", "Shoes"]
  validates :category, inclusion: { in: CATEGORY }
  validates :brand, presence: true
  validates :price, presence: true
  validates :category, presence: true
  validates :name, presence: true
  validates :gender, presence: true
  validates :comment, presence: true
  include PgSearch::Model
pg_search_scope :search,
  against: [ :name, :brand, :category, :tag ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items
  has_many :bookings
  has_many :bookings_as_owner, through: :items, source: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit::Authorization

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end



end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking)
    @user = current_user
  end

  def show
    authorize(@booking)
  end

  def new
    @item = Item.find(params[:item_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @item = Item.find(params[:item_id])
    @booking = Booking.new(booking_params)
    @booking.status = "pending"
    @booking.user = current_user
    @booking.item = @item
    authorize(@booking)
    if @booking.save
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    if @booking.update(edit_booking_params)
      redirect_to bookings_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :address, :city, :state, :zipcode, :comment)
  end

  def edit_booking_params
    params.require(:booking).permit(:start_date, :end_date, :comment, :address, :city, :state, :zipcode, :status)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @items = policy_scope(Item)
    if params[:category].present?
      @items = @items.where("lower(category) = ?", params[:category].downcase)
    end
    if params[:query].present?
      @items = @items.search(params[:query])
    end
  end

  def show
    @item = Item.find(params[:id])
    authorize(@item)
  end

  def new
    @item = Item.new
    authorize(@item)
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    authorize(@item)
    if @item.save
      redirect_to bookings_path
    else
      render :new, status, :unprocessable_entity
    end
  end

  def edit
    @item = Item.find(params[:id])
    authorize @item
  end

  def update
    @item = Item.find(params[:id])
    authorize @item
    if @item.update(edit_item_params)
      redirect_to bookings_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item = Item.find(params[:id])
    authorize @item
    @item.destroy
    redirect_to bookings_path
  end

  private

  def item_params
    params.require(:item).permit(:category, :brand, :price, :name, :gender, :comment, :tag, :photo)
  end

  def edit_item_params
    params.require(:item).permit(:category, :brand, :price, :name, :gender, :comment, :tag, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container items">
  <div class="header">
    <h1>Update request</h1>
  </div>
  <h3><%= @booking.item.name %></h3>
  <h3><%= @booking.start_date %> to <%= @booking.end_date %></h3>
  <h3>$<%= @booking.item.price * (@booking.end_date - @booking.start_date).to_i %> total</h3>
  <%= simple_form_for @booking do |f| %>
    <%= f.input :status, collection: Booking::STATUS, prompt: 'Choose a status' %>
    <%= f.input :comment, placeholder: "Optional: Requests or notes can go here..." %>
    <%= f.submit value:"Update" ,class:"button" %>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <div class="row justify-content-evenly  card-bookings-buttons">
    <div class="col-2 text-center">
      <%= link_to items_path, class: "back-button" do %>
        <i class="fa-solid fa-arrow-left"></i> NEW IN
      <% end %>
    </div>
    <h2 class="header-bookings col-2">Your Closet</h2>
    <div class="col-2 text-center">
      <%= link_to new_item_path, class: "back-button" do %>
        ADD ITEM <i class="fa-solid fa-plus"></i>
      <% end %>
    </div>
    <div class=" d-flex mb-5">
      <div class="col">
        <h3 class="text-center header">Reservations</h3>
        <div class="cards-half">
          <% @bookings.each do |booking| %>
            <div class="item-card">
              <% if booking.item.photo.attached? %>
                <%= cl_image_tag(booking.item.photo.key) %>
              <% else %>
                <%= image_tag(booking.item.image_url) %>
              <% end %>
              <div class="card-info">
                <h2><%= booking.item.name %></h2>
                <p>$<%= booking.item.price * (booking.end_date - booking.start_date).to_i %> total</p>
                <div>
                  <%= booking.status %>
                  <p>From: <%= booking.start_date %> </p>
                  <p> Until: <%= booking.end_date %></p>
                  <p> Zipcode: <%= booking.zipcode %></p>
                  <p> Address: <%= booking.address %></p>
                  <p> City: <%= booking.city %></p>
                  <p> State: <%= booking.state %></p>
                </div>
              </div>
              <div class="d-flex mb-2">
                <div>
                  <% if policy(booking).edit? %>
                    <%= link_to "Edit", edit_booking_path(booking), class: "button me-1 button-space" %>
                  <% end %>
                </div>
                <div class="d-flex mb-2" >
                  <% if policy(booking).destroy? %>
                    <%= link_to "Remove", booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Remove request?" }, class: "button button-space" %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col">
        <h3 class="text-center header">My Items</h3>
        <div class="cards-half">
          <% @current_user.items.each do |item| %>
            <div class="item-card">
              <% if item.photo.attached? %>
                <%= cl_image_tag(item.photo.key) %>
              <% else %>
                <%= image_tag(item.image_url) %>
              <% end %>
              <div class="card-info">
                <h2> <%= item.brand %> </h2>
                <p> <%= item.name  %></p>
                <h2> $<%= item.price %> / day</h2>
              </div>
              <div class="d-flex mb-2">
                <% if policy(item).edit? %>
                  <%= link_to "Edit", edit_item_path(item), class: "button me-1 button-space" %>
                <% end %>
                <% if policy(item).destroy? %>
                  <%= link_to "Remove", item_path(item), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove this item?" }, class: "button" %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/bookings/new.html.erb
<div class="container items">
  <div>
    <%= link_to items_path, class: "back-button" do %>
      <i class="fa-solid fa-arrow-left"></i> BACK
    <% end %>
  </div>
  <div class="d-flex justify-content-around">
    <div class="mb-5">
      <h2>Enter your information</h2>
      <%= simple_form_for [@item, @booking] do |f| %>
        <%= f.input :address, as: :text %>
        <%= f.input :city %>
        <%= f.input :state %>
        <%= f.input :zipcode %>
        <div class="d-flex ">
          <%= f.input :start_date, html5: true, input_html: {min: (Date.today + 7) } %>
          <%= f.input :end_date, html5: true, input_html: {min: (Date.today + 7) }  %>
        </div>
        <div class="">
          <%= f.input :comment, placeholder: "Optional: Requests or notes can go here..." %>
        </div>
        <%= f.submit value:"Reserve", class:"button" %>
      <% end %>
    </div>
    <%# <div class="row"> %>
    <div class="item-show-card">
      <% if @item.photo.attached? %>
        <%= cl_image_tag @item.photo.key, class: "img-fluid img-thumbnail"%>
      <% else %>
        <%= image_tag @item.image_url, class: "img-fluid img-thumbnail"%>
      <% end %>
      <div class="item-show-card-info">
        <h2><%= @item.name %></h2>
        <p class="mt-3">Brand: <%= @item.brand %></p>
        <p>Price: $<%= @item.price %> / day</p>
      </div>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<div class="container mb-5">
  <div class="m-2">
    <%= link_to bookings_path, class: "back-button" do %>
      <i class="fa-solid fa-arrow-left"></i> NEW IN
    <% end %>
  </div>
  <div class="empty-div-navbar-fix mt-5">
    <h1>Edit item </h1>
    <%= simple_form_for [@item] do |f| %>
      <div class="d-flex ">
        <div class="col-6">
          <%= f.input :brand%>
          <%= f.input :name%>
          <%= f.input :price, as:"text"%>
          <%= f.input :comment%>
          <%= f.input :tag%>
          <%= f.input :photo, as: :file %>
          <div class="d-flex justify-content-between">
            <%= f.input :category, collection: Item::CATEGORY, prompt: 'Choose a category' %>
            <%= f.input :gender, collection: ['Womens', 'Mens', 'Neutral'], prompt: 'Choose a gender' %>
          </div>
          <%= f.submit value:"Submit", class:"button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/items/index.html.erb
<% if params[:category].present? %>
  <h2 class="header"> <%= params[:category].upcase %> </h2>
<% elsif params[:query].present? %>

  <h3 class="header">Results for:<br>

    <%= params[:query] %></h3>
<% else %>
  <h2 class="header">NEW IN</h2>
<% end %>
<div class="search">
  <div id="search_bar">
    <%= form_with url: items_path, method: :get, class: "d-flex"  do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search your brand"
            %>
      <%= submit_tag "Search", name: "", class: "button" %>
    <% end %>
  </div>
</div>

<div class="container mb-5">

  <div class="m-2">
    <%= link_to root_path, class: "back-button" do %>
      <i class="fa-solid fa-arrow-left"></i> HOME
    <% end %>
  </div>
  <div class="cards">
    <% @items.each do |item| %>
      <div class="item-card">
        <div class="HeartAnimation heart-position " data-controller="heart" data-action="click->heart#animate"></div>
        <%= link_to item_path(item) do %>
          <% if item.photo.attached? %>
            <%= cl_image_tag(item.photo.key) %>
          <% else %>
            <%= image_tag(item.image_url) %>
          <% end %>
        <% end %>
        <div class="card-info d-flex justify-content-between">
          <div>
            <h2> <%= item.brand %> </h2>
            <p> <%= item.name  %></p>
            <h2> $<%= item.price %> / day</h2>
          </div>
          <div>
            <%= link_to "Reserve", new_item_booking_path(item), class: "button" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<div class="container mb-5">
  <div class="m-2">
    <%= link_to bookings_path, class: "back-button" do %>
      <i class="fa-solid fa-arrow-left"></i> NEW IN
    <% end %>
  </div>
  <div class="empty-div-navbar-fix mt-5">
    <h1>Add item </h1>
    <%= simple_form_for [@item] do |f| %>
      <div class="d-flex ">
        <div class="col-6">
          <%= f.input :brand, placeholder: "Brand..." %>
          <%= f.input :name, placeholder: "Item name..." %>
          <%= f.input :price, placeholder: "Price..." %>
          <%= f.input :comment, placeholder: "Details..." %>
          <%= f.input :tag, placeholder: "Color, size, etc.." %>
          <%= f.input :photo, as: :file %>
          <div class="d-flex justify-content-between">
            <%= f.input :category, collection: Item::CATEGORY, prompt: 'Choose a category' %>
            <%= f.input :gender, collection: ['Womens', 'Mens', 'Neutral'], prompt: 'Choose a gender' %>
          </div>
          <%= f.submit value:"Submit", class:"button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/items/show.html.erb
<div class="container mb-4">
  <div class="row">
    <div class="col-sm-4">
      <div class="m-2">
        <%= link_to items_path, class: "back-button" do %>
          <i class="fa-solid fa-arrow-left"></i> BACK
        <% end %>
      </div>
      <%# <div class="img-fluid img-thumbnail"> %>
      <% if @item.photo.attached? %>
        <%= cl_image_tag @item.photo.key, class: "img-fluid img-thumbnail"%>
      <% else %>
        <%= image_tag @item.image_url, class: "img-fluid img-thumbnail"%>
      <% end %>
      <%# </div> %>
    </div>
    <div class="col-sm-8 d-flex justify-content-center align-items-center">
      <div class="col-md-8 mt-6">
        <h3 ><%= @item.name %></h3>
        <p class="mt-3">Brand: <%= @item.brand %></p>
        <p>Price: $<%= @item.price %> / day</p>
        <p>Detail: <%= @item.comment %> </p>
        <%= link_to "Reserve item", new_item_booking_path(@item), class: "button mt-1" %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Luxifi</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>

  <div class="navbar fixed-top">
    <div class="navbar-flex">
      </div>
    <div class="navbar-flex text-center">
  <h1><a style="text-decoration:none; color:#3B3B3B;" href=/>LUXIFI</a></h1>


  <p style="font-family: Nanum Myeongjo">Designers |
  <a style="text-decoration: none; color: #3B3B3B;" href="/items?category=clothing">Clothing</a> |
  <a style="text-decoration: none; color: #3B3B3B;" href="/items?category=shoes">Shoes</a> |
  <a style="text-decoration: none; color: #3B3B3B;" href="/items?category=bags">Bags</a>
  </p>

   </div>
   <div class="navbar-flex">
     <ul class="justify-content-end">
      <li><a href="/items"><i class="fa-solid fa-heart" style="color: #000000;"></i></a></li>
      <li><a href="/items"><i class="fa-solid fa-magnifying-glass" style="color: #000000;"></i></a></li>
      <li><a href="users/sign_in"><i class="fa-solid fa-user" style="color: #000000;"></i></a></li>
      <li><a href="#"><i class="fa-solid fa-bookmark" style="color: #000205;"></i></a></li>
      <li><a href="/bookings"><i class="fa-solid fa-bag-shopping" style="color: #000000;"></i></a></li>
    </ul>
    </div>
</div>


    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="video-container">
  <video autoplay muted loop class="w-100">
    <source src="/videos/homepagevideo.mp4" type="video/mp4">
    Your browser does not support the video tag.
  </video>
</div>


</div>
    <div class="overlayText">
    <h1><a id="topText" href=/items>New in</a><h1>
    </div>

  <div class="container fw-lighter text-center">
    <div class="sloganposition">
  <h1><a id="slogan">Try designer brands, without the designer price</a><h1>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>